# Example Home Assistant Configuration for Battery Runtime Calculator

# Add this to your configuration.yaml lovelace section (if using legacy method)
# Note: The modern way is to add resources through the UI
lovelace:
  resources:
    - url: /local/battery-runtime-calculator.js
      type: module

# Example Lovelace card configurations

# Basic configuration
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption

# Advanced configuration with all options
- type: custom:battery-runtime-calculator
  name: "House Battery Status"
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  generation_entity: sensor.solar_power
  grid_charging_entity: sensor.grid_power
  battery_charging_entity: sensor.battery_charge_power
  battery_discharging_entity: sensor.battery_discharge_power
  battery_capacity: 13.5  # kWh
  show_title: true
  show_battery_icon: true
  show_battery_percentage: true
  show_capacity: true
  show_battery_graph: true
  show_house_usage: true
  show_battery_discharge: true
  show_battery_charge: true
  show_solar: true
  show_grid_power: true
  show_runtime: true
  show_charge_time: true
  show_last_update: true
  update_interval: 30

# Minimal configuration (only runtime)
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  show_title: false
  show_battery_icon: false
  show_battery_percentage: false
  show_capacity: false
  show_battery_graph: false
  show_house_usage: false
  show_battery_discharge: false
  show_battery_charge: false
  show_solar: false
  show_grid_power: false
  show_last_update: false
  show_charge_time: false
  show_runtime: true

# Battery graph only
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  show_title: false
  show_battery_icon: false
  show_battery_percentage: false
  show_capacity: false
  show_house_usage: false
  show_battery_discharge: false
  show_battery_charge: false
  show_solar: false
  show_grid_power: false
  show_runtime: false
  show_charge_time: false
  show_last_update: false
  show_battery_graph: true

# Power monitoring dashboard
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  generation_entity: sensor.solar_power
  grid_charging_entity: sensor.grid_power
  show_title: false
  show_battery_icon: false
  show_battery_percentage: false
  show_capacity: false
  show_runtime: false
  show_charge_time: false
  show_last_update: false
  show_battery_graph: false

# Example with different battery systems

# LuxPower integration (Recommended)
- type: custom:battery-runtime-calculator
  name: "LuxPower Battery"
  battery_entity: sensor.luxpower_battery_soc
  power_entity: sensor.luxpower_load_power
  generation_entity: sensor.luxpower_solar_power
  grid_charging_entity: sensor.luxpower_grid_power
  battery_charging_entity: sensor.luxpower_battery_charge_power
  battery_discharging_entity: sensor.luxpower_battery_discharge_power
  battery_capacity: 23.8

# SolarEdge integration
- type: custom:battery-runtime-calculator
  name: "SolarEdge Battery"
  battery_entity: sensor.solaredge_battery_level
  power_entity: sensor.solaredge_consumption
  battery_capacity: 13.5

# Tesla Powerwall integration
- type: custom:battery-runtime-calculator
  name: "Powerwall Status"
  battery_entity: sensor.powerwall_battery_level
  power_entity: sensor.powerwall_load
  battery_capacity: 13.5

# Generic battery monitor
- type: custom:battery-runtime-calculator
  name: "Backup Battery"
  battery_entity: sensor.battery_percentage
  power_entity: sensor.total_power_usage
  battery_capacity: 10.0

# Multiple battery systems
- type: vertical-stack
  cards:
    - type: custom:battery-runtime-calculator
      name: "Main Battery"
      battery_entity: sensor.main_battery_level
      power_entity: sensor.main_power_consumption
      battery_capacity: 13.5
    - type: custom:battery-runtime-calculator
      name: "Backup Battery"
      battery_entity: sensor.backup_battery_level
      power_entity: sensor.backup_power_consumption
      battery_capacity: 5.0