# Example Home Assistant Configuration for Battery Runtime Calculator

# Add this to your configuration.yaml lovelace section (if using legacy method)
# Note: The modern way is to add resources through the UI
lovelace:
  resources:
    - url: /local/battery-runtime-calculator.js
      type: module

# Example Lovelace card configurations

# Basic configuration
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption

# Advanced configuration with all options
- type: custom:battery-runtime-calculator
  name: "Home Battery Status"
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  battery_capacity: 13.5  # kWh
  show_power: true
  show_capacity: true
  show_runtime: true
  update_interval: 30

# Minimal configuration (only runtime)
- type: custom:battery-runtime-calculator
  battery_entity: sensor.battery_level
  power_entity: sensor.home_power_consumption
  show_power: false
  show_capacity: false
  show_runtime: true

# Example with different battery systems

# SolarEdge integration
- type: custom:battery-runtime-calculator
  name: "SolarEdge Battery"
  battery_entity: sensor.solaredge_battery_level
  power_entity: sensor.solaredge_consumption
  battery_capacity: 13.5

# Tesla Powerwall integration
- type: custom:battery-runtime-calculator
  name: "Powerwall Status"
  battery_entity: sensor.powerwall_battery_level
  power_entity: sensor.powerwall_load
  battery_capacity: 13.5

# Generic battery monitor
- type: custom:battery-runtime-calculator
  name: "Backup Battery"
  battery_entity: sensor.battery_percentage
  power_entity: sensor.total_power_usage
  battery_capacity: 10.0

# Multiple battery systems
- type: vertical-stack
  cards:
    - type: custom:battery-runtime-calculator
      name: "Main Battery"
      battery_entity: sensor.main_battery_level
      power_entity: sensor.main_power_consumption
      battery_capacity: 13.5
    - type: custom:battery-runtime-calculator
      name: "Backup Battery"
      battery_entity: sensor.backup_battery_level
      power_entity: sensor.backup_power_consumption
      battery_capacity: 5.0
